POST http://localhost:3003/user
Content-Type: application/json

{
    "name": "Lua",
    "nickname": "lua_123",
    "email": "lua_123@hotmail.com"
}

###


GET http://localhost:3003/user/1

###

POST http://localhost:3003/task
Content-Type: application/json

{
    "title": "Lavar louça",
    "description": "lavar a louça",
    "limit_date": "2022-06-15",
    "user_author_id": 4
}