GET http://localhost:3003/atores/002

###

GET http://localhost:3003/atores/genero/female

###

PUT http://localhost:3003/atores/atualizar_salario/001

{
    "salary": 100000
}

###

DELETE http://localhost:3003/atores/deletar_atores/001

###

GET http://localhost:3003/atores/media_salarial/male

###

GET http://localhost:3003/atores_por_id/002

###

GET http://localhost:3003/atores_by_query?gender=female

###

POST http://localhost:3003/atores
Content-Type: application/json

{
    "name": "Matheus",
    "salary": 96842963,
    "birth_date": "1995-08-22",
    "gender": "male"
}